In [1]:
import numpy as np

In [2]:
import cv2

In [3]:
#Initializing a black canvas
canvas = np.zeros((300, 300, 3), dtype='uint8')
canvas.shape

(300, 300, 3)

In [4]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
green = (0, 255, 0)

In [6]:
#Drwaing a green line
#cv2.line(image, start_points, end_points, color)
cv2.line(canvas, (0, 0), (300, 300), green)

array([[[  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0]]

In [7]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
red = (0, 0, 255)

In [9]:
#Drawing a red line of width 3px
#cv2.line(image, start_points, end_points, color, <line thickness>)
cv2.line(canvas, (300, 0), (0, 300), red, 3)

array([[[  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0]]

In [10]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
#Drawing a red rectangle 
#cv2.rectangle(image, left_top_corner, right_down_corner, color)
cv2.rectangle(canvas, (4, 100), (80, 150), red)

array([[[  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0]]

In [12]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#Drawing a red rectangle of width 4
cv2.rectangle(canvas, (50, 200), (200, 225), red, 4)

array([[[  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0]]

In [14]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
#Drawing a blue rectangle with full colour
blue = (255, 0, 0)

In [19]:
#cv2.rectangle(image, left_top_corner, right_down_corner, color, <line thickness>)
#line thickness = -1 represents full coloured rectangle
cv2.rectangle(canvas, (200, 50), (225, 125), blue, -1)

array([[[  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0, 255,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0, 255,   0]]

In [20]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
#Lets create a bulls eye image
canvas2 = np.zeros((300, 300, 3), dtype='uint8')

In [22]:
#Finding centers of the image
(centerX, centerY) = (canvas2.shape[1]//2, canvas2.shape[0]//2)

In [23]:
white = (255, 255, 255)

In [24]:
#Drawing circles with different radius
#cv2.circle(image, centers, radius, color)
for radius in range(0, 151, 25):
    cv2.circle(canvas2, (centerX, centerY), radius, white)

In [26]:
cv2.imshow("Canvas", canvas2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
#Lets draw some random drawing
for i in range(0, 25):
    radius = np.random.randint(5, high=200)
    color = np.random.randint(0, high=256, size=(3,)).tolist()
    center = np.random.randint(0, high=300, size=(2,))
    cv2.circle(canvas2, tuple(center), radius, color, -1)

In [31]:
cv2.imshow("Canvas", canvas2)
cv2.waitKey(0)
cv2.destroyAllWindows()